- name: Create debian lxc template
  community.general.lxc_container:
    name: template-debian
    template: download
    backing_store: "{{ lxc_backing_storage }}"
    state: stopped
    container_config:
      - "lxc.net.0.ipv4.address = 10.0.3.10/24"
    template_options: --keyserver hkp://keyserver.ubuntu.com -d debian -r bullseye -a amd64
  tags: yyy

- name: Start debian container
  shell: lxc-unpriv-start -n template-debian
  tags: yyy
