---
# tasks file for roles/basic

- name: update cache
  become: yes
  apt:
    update_cache: true

- include: zsh.yml
- include: vim.yml
- include: lf.yml
- include: tmux.yml
- include: git.yml
- include: python.yml

- name: add some basic packages  
  become: yes
  apt:
    name:
      - file
      - htop
      - mlocate
