- name: install zsh packages
  become: yes
  apt:
    name:
      - zsh
      - zsh-syntax-highlighting
      - gawk       

- name: create zsh config
  copy:
    src:  configs/zshrc
    dest: "/home/{{username}}/.zshrc"

- name: set user SHELL to zsh    
  become: yes
  user:
    name: "{{username}}"
    shell: /usr/bin/zsh
    groups: sudo
