---
# tasks file for roles/ssh-access

- name: add install script to rootfs
  become: yes
  template:
    src: templates/add-ssh-access.sh
    dest: /home/{{username}}/.local/share/lxc/template-debian/rootfs/add-ssh-access.sh
    owner: '100000'
    group: '100000'
    mode: '0755'
  tags: yyy

- name: execute install script
  shell:
    cmd: |
      #lxc-stop -k -n template-debian
      #lxc-unpriv-start -n template-debian
      lxc-unpriv-attach -n template-debian -u 0 -v TERM=xterm -v PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin -- /add-ssh-access.sh
      #lxc-stop -k -n template-debian
  tags: yyy

